image: nfcore/gitpod:latest
tasks:
  - name: Update Nextflow and setup pre-commit
    init: pip install -r requirements.txt
    command: |
      pre-commit install --install-hooks
      nextflow self-update {%- if code_linters %}
      python -m ipykernel install --user --name=base --display-name "Python (Conda Base)"

vscode:
  extensions:
    - codezombiech.gitignore # Language support for .gitignore files
    - esbenp.prettier-vscode # Markdown/CommonMark linting and style checking for Visual Studio Code
    - EditorConfig.EditorConfig # override user/workspace settings with settings found in .editorconfig files
    - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
    - nextflow.nextflow # Nextflow syntax highlighting
    - oderwat.indent-rainbow # Highlight indentation level
    - streetsidesoftware.code-spell-checker # Spelling checker for source code
    - ritwickdey.LiveServer # See html pages in VS
    - ms-toolsai.jupyter # Jupyter Notebook for VS
    - ms-python.python

